
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FN FNL FNR LBRACE NAME NUMBER RBRACE SEMI STRINGkeyword : NAME NUMBER SEMI LBRACE RBRACE STRING FN FNL FNR'
    
_lr_action_items = {'NAME':([0,],[2,]),'$end':([1,10,],[0,-1,]),'NUMBER':([2,],[3,]),'SEMI':([3,],[4,]),'LBRACE':([4,],[5,]),'RBRACE':([5,],[6,]),'STRING':([6,],[7,]),'FN':([7,],[8,]),'FNL':([8,],[9,]),'FNR':([9,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'keyword':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> keyword","S'",1,None,None,None),
  ('keyword -> NAME NUMBER SEMI LBRACE RBRACE STRING FN FNL FNR','keyword',9,'p_keyword','index.py',7),
]
